/**
 * Browser-side Supabase client
 *
 * This file is automatically generated. Do not edit it directly.
 *
 * Creates a Supabase client instance for use in browser-side code.
 * Uses the public anon key for client-side operations with RLS policies enforced.
 * Configured with PKCE flow for secure authentication without redirect redirects.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable automatic session detection from URL
    flowType: 'pkce', // Use PKCE flow which doesn't redirect
  }
});